import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const pages = [
		{ href: "/auth/login", title: "Login", id: 1 },
		{ id: 2, href: "/auth/signup", title: "Signup" },
	];

	return (
		<>
			<Head>
				<title>Social Web App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="px-5 py-5">
				<h1 className="text-[30px] text-bold">Welcome to social web app</h1>
				<p className="text-[20px] text-normal">
					Note: This website is currently in the process of building
				</p>
				<h3 className="mt-[25px] mb-[10px] text-[25px] text-bold ">Pages:</h3>
				<div className="px-2 flex flex-col">
					{pages.map((page) => (
						<Link
							key={page.id}
							href={page.href}
							className="text-blue-500 underline text-[17px] py-[5px]"
						>
							{page.title}
						</Link>
					))}
				</div>
			</main>
		</>
	);
}
